### ISSUE TITLE
Delete extra '\'

### ISSUE THREAD

**Issue by m-kirihara** [ayatakesi/ayatakesi.github.io#2]
When reading the 56th-61st lines of the HTML file in https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Char-Syntax.html ,
I think the 86th line of the HTML file in https://github.com/ayatakesi/ayatakesi.github.io/blob/master/lispref/translation_HEAD/html/Basic-Char-Syntax.html should be modified with the replacement of
"…もつ場合には&lsquo;<samp>\\</samp>&rsquo;でクォート…" and "…たとえば&lsquo;<samp>?\\(</samp>&rsquo;が…"
to
"…もつ場合には&lsquo;<samp>\</samp>&rsquo;でクォート…" and "…たとえば&lsquo;<samp>?\(</samp>&rsquo;が…", respectively.
Otherwise, we cannot read the page properly: https://ayatakesi.github.io/lispref/28.2/html/Basic-Char-Syntax.html .

Sorry for the inconvenience report. Today is the first day for me to use GitHub.

**Comment by m-kirihara** [comment]
すみません，プレーンテキストで表示されないので私の指摘がよくわからないかと思いますが，示していますGNUのサイトの HTML ファイルの 56行目 から 61行目 と御自身の HTML ファイルの 86行目 を見て，バックスラッシュの個数を比較されたらおわかりになると思います．
(当方，Emacs Lisp の勉強中で，あなたの翻訳が大変役に立っています．)

**Comment by ayatakesi** [comment]
返事遅れて申し訳ありません。確かにご指摘の通りでした、修整させていただきます。
ありがとうございましたm(_ _)m

**Comment by m-kirihara** [comment]
修正して頂き，ありがとうございます．
Close します．
