### ISSUE TITLE
typo in Sequence-Type.html

### ISSUE THREAD

**Issue by m-kirihara** [ayatakesi/ayatakesi.github.io#3]
Pull request するべきなのでしょうけど…，
Sequence-Type.html の 79行目 において

<p>シーケンスは読み取りにより常に新たに作成されるやめ、

とあるのは，

<p>シーケンスは読み取りにより常に新たに作成されるため、

の間違いだと思います．

**Comment by ayatakesi** [comment]
こちらもご指摘のようにtypoです。修整提案採用させていただきます、ありがとうございました
m(_ _)m

**Comment by m-kirihara** [comment]
こちらも修正して頂き，ありがとうございます．
Close します．
